---
argument_specs:
  main:
    short_description: 'Update compose projects'
    description:
      - 'Update all or just some compose projects'
    options:
      update_compose_projects_json_path:
        type: 'str'
        required: false
        default: '/opt/docker/'
        description:
          - 'Path, where the compose_projects.json is created/searched'

      update_compose_projects_ignore_projects:
        type: 'list'
        elements: 'str'
        required: false
        default: []
        description:
          - 'List of projects (full path) which should be ignored'
          - 'ex. /opt/docker/traefik'

      update_compose_projects_list:
        type: 'list'
        elements: 'str'
        required: false
        default: []
        description:
          - 'List of projects to update (full path)'
          - 'ex. /opt/docker/traefik'
          - 'When this var is set, only the listed projects will be updated'
...
