---
setup_vault_folder_owner: root
setup_vault_folder_group: root
setup_vault_create_folder: false

setup_vault_image: hashicorp/vault
setup_vault_version: latest

setup_vault_create_network: false

setup_vault_storage: 'file'
setup_vault_transit: false
setup_vault_expose: true
setup_vault_external_port: 8201
setup_vault_transit_keyname: 'unseal_key'
setup_vault_disable_mlock: "false"

setup_vault_data_path: '{{ setup_vault_folder_path }}/data'

setup_vault_traefik: false
setup_vault_traefik_default_labels: false
setup_vault_traefik_custom_labels: ''

setup_vault_bind_address: "[::]"
setup_vault_bind_port: 8200

setup_vault_cluster_bind_address: "[::]"
setup_vault_cluster_bind_port: 8300

setup_vault_cluster: false
setup_vault_cluster_expose: false
setup_vault_cluster_external_port: 8300
...
