---
- name: Update all projects
  ansible.builtin.include_tasks: update_all.yaml
  when: update_compose_projects_list is undefined or update_compose_projects_list | length == 0

- name: Update list of projects
  ansible.builtin.include_tasks: update_list.yaml
  when:
    - update_compose_projects_list is defined
    - update_compose_projects_list | length > 0
...
