---
argument_specs:
  main:
    short_description: Setup Vault with compose
    description:
      - Setup Vault with compose
    options:
      setup_vault_folder_path:
        type: str
        required: true
        description:
          - Path of the compose-project
          - Must be an absolute path

      setup_vault_folder_owner:
        type: str
        required: false
        default: root
        description:
          - Owner of the Folder and Files

      setup_vault_folder_group:
        type: str
        required: false
        default: root
        description:
          - Group of the Folder and Files

      setup_vault_create_folder:
        type: bool
        required: false
        default: false
        description:
          - Set, if the Folder should be created

      setup_vault_name:
        type: str
        required: true
        description:
          - Name for the project
          - Used for the composefile and traefik-router

      setup_vault_image:
        type: str
        required: false
        default: hashicorp/vault
        description:
          - Image to use for vault

      setup_vault_version:
        type: str
        required: false
        default: latest
        description:
          - Imagetag to use for vault

      setup_vault_network:
        type: str
        required: false
        description:
          - Set, if an external network should be used for vault

      setup_vault_create_network:
        type: bool
        required: false
        default: false
        description:
          - Set, if the network for vault should be created

      setup_vault_expose:
        type: bool
        required: false
        default: true
        description:
          - Set to false, if traefik is used or the vault should not expose a port

      setup_vault_external_port:
        type: str
        required: false
        default: 8201
        description:
          - Port, on which vault should be exposed

      setup_vault_data_path:
        type: str
        required: false
        default: ./data
        description:
          - 'Path, where the vault data should be stored'
          - 'Must be an absolute path'
          - 'If you want to store it in the compose-folder, you can use something like: {{ setup_vault_folder_path }}/data'

      setup_vault_traefik:
        type: bool
        required: false
        default: false
        description:
          - Should traefik be enabled for the compose project

      setup_vault_traefik_default_labels:
        type: bool
        required: false
        default: true
        description:
          - Set to false, if the default-labels for traefik should not be used
          - Only required, when traefik is used

      setup_vault_traefik_fqdn:
        type: str
        required: false
        description:
          - FQDN, on which the vault should be exposed
          - Only required when traefik is used

      setup_vault_traefik_custom_labels:
        type: str
        required: false
        default: ''
        description:
          - Custom traefik-labels to set
          - Should be set as multiline-string
          - Only required when traefik is used

      setup_vault_transit:
        type: bool
        required: false
        default: false
        description:
          - Set, to enable the transit-engine for vault (auto unsealing)

      setup_vault_transit_address:
        type: str
        required: false
        default: ''
        description:
          - Set to the address of the unsealing-vault
          - Only needed, if setup_vault_transit is true

      setup_vault_storage:
        type: str
        required: false
        default: file
        choices:
          - file
          - raft
        description:
          - 'Storagetype, which should be used for the vault'

      setup_vault_transit_keyname:
        type: str
        required: false
        default: 'unseal_key'
        description:
          - 'Name of the Key in the unsealing-vault'
          - 'Should be unique in the unsealing-vault'

      setup_vault_transit_token:
        type: str
        required: false
        description:
          - Token for the autounsealing, only used when setup_vault_transit is true
          - Will be set in the vault_env file for autounsealing

      setup_vault_disable_mlock:
        type: str
        required: false
        default: false
        description:
          - Should mlock being disabled or enabled

      setup_vault_bind_address:
        type: str
        required: false
        default: 0.0.0.0
        description:
          - 'Address, to bind to'

      setup_vault_bind_port:
        type: str
        required: false
        default: 8200
        description:
          - 'Port, to bind to'

      setup_vault_cluster_bind_address:
        type: str
        required: false
        default: 0.0.0.0
        description:
          - 'Address, to bind the cluster to'
          - 'Only required when setup_vault_cluster is true'

      setup_vault_cluster_bind_port:
        type: str
        required: false
        default: 8300
        description:
          - 'Port, to bind the cluster to'
          - 'Only required when setup_vault_cluster is true'

      setup_vault_cluster:
        type: bool
        required: false
        default: false
        description:
          - 'Should the instance be part of a cluster'

      setup_vault_cluster_expose:
        type: bool
        required: false
        default: true
        description:
          - Set to false, if traefik is used or the vault cluster should not expose a port

      setup_vault_cluster_external_port:
        type: str
        required: false
        default: 8300
        description:
          - Port, on which vault cluster should be exposed
...
